services:
  nginx:
    build: nginx_server
    ports:
      - "8080:80"
  postgres:
    image: postgres
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lenta
  adminer:
    image: adminer
    ports:
      - "8081:8080"
  golang:
    build: golang
    restart: always
    depends_on:
      - postgres